### PR TITLE
YALB-1164 - OPAC: Update admin toolbar icons | 1461 - OPAC: Implement new admin colors and fonts

### PR DESCRIPTION
**Pull request by joetower**
### Description of work
- Test here: https://github.com/yalesites-org/yalesites-project/pull/358

### CODE REVIEW

**Review by codechefmarc — CHANGES_REQUESTED** [review]
Similar to what Mike T. pointed out with "white" text over a while background, here are a few others I found:

1. Status Report

Screenshot 2023-07-20 at 11 51 06 AM

2. Appearance descriptions of themes

Screenshot 2023-07-20 at 11 52 21 AM

Also I wanted to point out the color difference of the buttons, not sure if that is something we want to change or not, but thought I'd point it out:

Screenshot 2023-07-20 at 11 51 21 AM

**Comment by joetower** [comment]
@codechefmarc I pushed up fixes for your first two items. 

I see your point about the buttons. My initial thought is that because that other instance of a button is on top of our `--wool` color, it should be different, for contrast. I'll see what Mike Tullo says. Maybe we should change it to use a dark gray, instead.

**Comment by dblanken-yale** [comment]
Yes, the color differences on the buttons did stand out to me, especially the edit with the drop downs.  The others didn't seem out of place to me.

**Comment by joetower** [comment]
@dblanken-yale @codechefmarc What do you both think about changing them to the darkest gray? 

Screenshot-20230721143033-2519x1281

Otherwise, we could go with the same light blue. I just feel like the buttons, when that small, feel washed out against the wool background. 

Screenshot-20230721143355-2523x1327


What are your thoughts?

**Comment by dblanken-yale** [comment]
We'll see what others say, but my vote is for the lighter color.

**Comment by joetower** [comment]
@codechefmarc and @dblanken-yale This is ready for another look when you have time. 

I did change the dropdown button to match the other buttons. 

Could you please also add/edit content using layout-builder and make sure everything is legible. 

Thank you!

**Review by codechefmarc — APPROVED** [review]
Most of the others chimed in ahead of me - I poked around and it looked good to me, though I will have to admit that Mike Tullo is doing a great job at the details here. From what I saw, I'm approving.

**Pull request merged**
