### PR TITLE
YALB-635: wiring breadcrumbs

### PR DESCRIPTION
**Pull request by codeb-a**
### Description of work
- Adds  breadcrumbs to a page in the main menu.

### Functional testing steps:
- [ ] Navigate to site.
- [ ] Go to structure/menus/main navigation.
- [ ] In order to see breadcrumbs change hierarchy "example page/FAQ/News".
- [ ] Go to FAQ page or News page to verify breadcrumbs are working.

### CODE REVIEW

**Review by marcb4k — CHANGES_REQUESTED** [review]
The links I'm seeing in the breadcrumb are all the same. Looks like it's using the same link for all items from the last link in the list.

**Comment by ModulesUnraveled** [comment]
I think I've fixed the issue in the component library. So once that (and the `is_active` thing I asked you to do on the backend) is in, this should work correctly without any additional work here.

**Review by ModulesUnraveled — APPROVED** [review]
I updated the component library to include the work we've been doing and everything looks like it's working as expected now!

**Comment by marcb4k** [comment]
Mentioned in Slack to Brian, but just adding in here as well - this now works after the changes, but the mobile breadcrumb arrow doesn't seem to do anything.

**Comment by ModulesUnraveled** [comment]
@marcb4k I realized there were two issues.

1. The breadcrumb label wasn't showing
2. The javascript (to show the full list) wasn't working.

I fixed the first issue in the Component Library, and pulled that in here.
I fixed the second issue here (the library needed to be namespaced)

So, everything should be good to go now!

**Review by marcb4k — APPROVED** [review]

**Pull request merged**
