### PR TITLE
IYY-263:Show CAS'd content in search results

### PR DESCRIPTION
**Pull request by codechefmarc**
### Description of work
- Adds logic to disable the rendering of the teaser and content preview of CAS nodes based on the `field_login_required` field.
- Note: This is part of [PR-800](https://github.com/yalesites-org/yalesites-project/pull/800) in the main repo.

### Functional testing steps:
- [x] See [PR-800](https://github.com/yalesites-org/yalesites-project/pull/800) for testing instructions

### CODE REVIEW

**Comment by codechefmarc** [comment]
@joetower - Let me know if this is the best way to split these out - I assume this will help you add the lock icon to CAS-only titles.

**Comment by joetower** [comment]
@codechefmarc I pushed up fixes to this branch and a new CL branch (https://github.com/yalesites-org/component-library-twig/pull/435) and started a rebuild on the main project :+1: .

**Review by joetower — APPROVED** [review]
@codechefmarc This all looks great to me. :shipit: 

What say you @dblanken-yale ?

**Review by dblanken-yale — APPROVED** [review]
LGTM :D

**Pull request merged**
