### PR TITLE
YALB-713 video wiring

### PR DESCRIPTION
**Pull request by codeb-a**
### Description of work
- Wires the Video component to Drupal.

### Functional testing steps:
- [x] Navigate to site.
- [x] Add page content type.
- [x] Fill out title/add video component in content and fill out fields.
- [x] Click add media. Add video URL from youtube and save.
- [x] Verify video component is being displayed on a page.

### CODE REVIEW

**Review by ModulesUnraveled — CHANGES_REQUESTED** [review]
Looks like you somehow committed the entire `node_modules` directory here. That needs to be removed. I think if you run this from the Atomic root, it should fix it `git rm -rf --cached --ignore-unmatch node_modules`.

**Review by marcb4k — APPROVED** [review]
This worked for me only after I had used the script to pull in the component-library-twig develop branch. But all looks good!

**Review by ModulesUnraveled — APPROVED** [review]
Code looks good. We do need to make sure that automatic builds will use the correct version of the component library though. Let's jump on zoom right after standup, to make sure the process is understood.

**Review by ModulesUnraveled — APPROVED** [review]
Thanks! :shipit:

**Pull request merged**
