### PR TITLE
YALB-1198: Events: Exposed filters on dynamic list (BE)

### PR DESCRIPTION
**Pull request by codechefmarc**
### Description of work
- Adds markup to support ajax filtering for views for Calendar List.
- Main testing instructions here: https://github.com/yalesites-org/yalesites-project/pull/276
- Multidev here: https://pr-276-yalesites-platform.pantheonsite.io/

### Functional testing steps:
- [x] When testing the "Calendar List" (the built in block, not views), verify that by changing the event category and clicking "Apply" will use Ajax to refresh the results and not perform a full page refresh.

### CODE REVIEW

**Review by joetower — APPROVED** [review]
@codechefmarc Looks good :+1: 
https://pr-276-yalesites-platform.pantheonsite.io/standard-page-one

**Comment by joetower** [comment]
@codechefmarc I should have asked before approving: is there a separate ticket to theme this?

We should probably wrap the `exposed` form in a component wrapper, maybe the `before`, too?

**Comment by codechefmarc** [comment]
@joetower - I wasn't aware of a theming ticket for this but it should be pretty minimal so I can take care of that here. I may tap you for info but I can follow what you did for the search form as that is pretty similar is my guess.

**Review by joetower — APPROVED** [review]
@codechefmarc I added a template for `select.html.twig`. Please check that it all looks good on your end and this is looking great to me!

**Pull request merged**
