### PR TITLE
YALB-1394: Bug: Accessibility (FE)- Empty heading being inserted when user does not fill in heading field

### PR DESCRIPTION
**Pull request by dblanken-yale**
## [YALB-1394: Bug: Accessibility (FE)- Empty heading being inserted when user does not fill in heading field](https://yaleits.atlassian.net/browse/YALB-1394)

This PR is linked to [component-library-twig PR #274](https://github.com/yalesites-org/component-library-twig/pull/274).

The original implementation disregarded the accordion_items in the component library and rendered them in atomic.  This was causing a missing h2 level when no accordion title was present.

To fix this, we preprocess the paragraph__accordion_item to inject a new attribute that will hold the heading_level that should be used, defaulting to 3.

### Description of work
- Add preprocessor for accordion item paragraph to inject the heading level based on the accordion's overall heading presence
- Use the new variable in the paragraph--accordion-item twig file, defaulting to 3 (the original hardcoded value)

### Functional testing steps:
- [ ] Add an accordion block to a page, ensuring an overall title is present
- [ ] After saving, view the HTML and verify that each item is showing as a `h3`
- [ ] Edit the block and remove the overall title of the accordion and save
- [ ] After saving, view the HTML and verify that each item is showing as a `h2`

### CODE REVIEW

**Comment by dblanken-yale** [comment]
Hi @codechefmarc.  I went ahead and added you to both the CL and this PR to get your feedback.  I was able to inject the variable needed through a preprocess hook, but wanted to know when we talk tomorrow if that's the best idea for this case.  I really appreciate you taking the time to meet with me tomorrow.

@myvaughn I added you as well since you found this issue, so wanted you to be able to try it out to see if it works for you locally.  You should be able to run the same command I sent you earlier today and it'll switch both atomic and CL to these branches to try.

**Review by codechefmarc — APPROVED** [review]
Tested this out and I ran into an error, see screenshot:
Screenshot 2023-07-18 at 3 39 23 PM

I found that this was only an issue on a new node with a new accordion. I think because the paragraph entity has not yet been created. I've run into this too. So, I added a test before your work and pushed that change and it worked great on new nodes/new paragraphs as well as existing ones.

Nice work! I had done this before on paragraphs, but didn't realize that the `getParentEntity` would work for getting the block info. Neat.

Approved!

**Comment by dblanken** [comment]
@codechefmarc ah good call!

**Comment by dblanken-yale** [comment]
@codechefmarc Ah good call!

**Comment by dblanken-yale** [comment]
Yeah, `getParentEntity` was a shot in the dark from me and I was glad it worked!

**Pull request merged**
