### PR TITLE
YSP-559: Upgrade Node Packages

### PR DESCRIPTION
**Pull request by joetower**
### Description of work
- Updates node to v20
- Updates packages

### Functional testing steps:
- [ ] Verify there are no glaring issues when navigating https://pr-679-yalesites-platform.pantheonsite.io/
- [ ] Locally you can test by removing all the `node_modules` directories from each repository - component library and yalesites project, and running `nvm use` and/or `npm install` to use node 20, then `npm install` on each to install the updated packages.

### CODE REVIEW

**Review by codechefmarc — APPROVED** [review]
All comments are over in the main repo PR. Approved!

**Comment by dblanken-yale** [comment]
@joetower I did want to talk to you about ys_links since it's commented out, but running into some release candidate issues currently.  Do you have time next week to discuss?

**Review by dblanken-yale — APPROVED** [review]
A proper change; nice work orchestrating this in multiple repos!

**Comment by dblanken-yale** [comment]
Again, this has been updated to work with latest release changes and ys_links.  Please re-review.

**Comment by dblanken-yale** [comment]
Incorporating this into the Drupal 10.3 upgrade.  Closing.

**Pull request closed without merging**
